## ทดลองทำการ Evaluate


In [3]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# สมมุติว่ามี Ground Truth และ Predicted Text
ground_truth = "กรุงเทพมหานคร"
predicted_text = "กรุงเทหมาหา"

# สร้าง list ของตัวอักษรจาก Ground Truth และ Predicted Text
ground_truth_chars = list(ground_truth)
predicted_chars = list(predicted_text)

# เพิ่มความยาวของ list ให้ตรงกัน
max_len = max(len(ground_truth_chars), len(predicted_chars))
ground_truth_chars = ground_truth_chars + [''] * (max_len - len(ground_truth_chars))
predicted_chars = predicted_chars + [''] * (max_len - len(predicted_chars))

# สร้าง confusion matrix
cm = confusion_matrix(ground_truth_chars, predicted_chars, labels=np.unique(ground_truth_chars + predicted_chars))

# แสดง confusion matrix
print("Confusion Matrix:")
print(cm)

# แสดงผล classification report
print("Classification Report:")
print(classification_report(ground_truth_chars, predicted_chars))


Confusion Matrix:
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]]
Classification Report:
              precision    recall  f1-score   support

                   0.00      0.00      0.00         0
           ก       1.00      1.00      1.00         1
           ค       0.00      0.00      0.00         1
           ง       1.00      1.00      1.00         1
           ท       1.00      1.00      1.00         1
           น       0.00      0.00      0.00         1
           พ       0.00      0.00      0.00         1
           ม       1.00      1.00      1.00         1
           ร       1.00      0.50      0.67         2
           ห       0.00      0.00      0

/Users/gunnviryasiri/.pyenv/versions/3.11.0/envs/myenv3110/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/gunnviryasiri/.pyenv/versions/3.11.0/envs/myenv3110/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/gunnviryasiri/.pyenv/versions/3.11.0/envs/myenv3110/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control t