# ทำการเทรน
- หลังทำการรัน ย้ายไฟล์ gunn_trained_1.lstm ไปที่ไดเร็กทอรี Tesseract ที่ใช้เก็บไฟล์ .traineddata 
```
cp gunn_trained_1.lstm /Users/gunnviryasiri/pythainlp-data/tessdata/gunn.traineddata
```

In [13]:
import os
import subprocess

def convert_bmp_to_png(directory):
    for filename in os.listdir(directory):
        if filename.endswith(".bmp"):
            bmp_path = os.path.join(directory, filename)
            png_path = os.path.splitext(bmp_path)[0] + ".png"
            subprocess.run(["convert", bmp_path, png_path])

def generate_box_files(directory):
    for filename in os.listdir(directory):
        if filename.endswith(".png"):
            png_path = os.path.join(directory, filename)
            base_name = os.path.splitext(png_path)[0]
            subprocess.run(["tesseract", png_path, base_name, "-l", "tha", "--psm", "6", "batch.nochop", "makebox"])

def train_model(directory):
    for filename in os.listdir(directory):
        if filename.endswith(".png"):
            png_path = os.path.join(directory, filename)
            box_path = os.path.splitext(png_path)[0] + ".box"
            subprocess.run(["tesseract", png_path, box_path, "lstm.train"])

def extract_unicharset(directory):
    box_files = [os.path.join(directory, f) for f in os.listdir(directory) if f.endswith(".box")]
    subprocess.run(["unicharset_extractor", "--norm_mode", "3"] + box_files)

def combine_tessdata(tessdata_path, output_path):
    subprocess.run(["combine_tessdata", "-e", tessdata_path, output_path])

def main():
    # กำหนดเส้นทางโฟลเดอร์
    directory = "/Users/gunnviryasiri/Desktop/ocr/ThaiOCR/ThaiOCR-TrainigSet"  # แก้ไขเส้นทางนี้ให้ตรงกับตำแหน่งที่เก็บข้อมูล
    tessdata_path = "/Users/gunnviryasiri/pythainlp-data/tessdata/tha.traineddata"  # เส้นทางไปยังไฟล์ tha.traineddata
    # output_path = "tha.lstm"
    output_path = "gunn_trained_1.lstm"

    # แปลงไฟล์ BMP เป็น PNG
    convert_bmp_to_png(directory)

    # สร้างไฟล์ .box
    generate_box_files(directory)

    # ฝึกโมเดล
    train_model(directory)

    # สร้างไฟล์ unicharset
    extract_unicharset(directory)

    # สร้างไฟล์ training data
    combine_tessdata(tessdata_path, output_path)

    print("Training completed successfully!")

if __name__ == "__main__":
    main()

Extracting tessdata components from /Users/gunnviryasiri/pythainlp-data/tessdata/tha.traineddata
Wrote gunn_trained_1.lstm
Version:4.00.00alpha:tha:best2int20180322
0:config:size=27, offset=192
17:lstm:size=960082, offset=219
18:lstm-punc-dawg:size=2914, offset=960301
19:lstm-word-dawg:size=101722, offset=963215
20:lstm-number-dawg:size=42, offset=1064937
21:lstm-unicharset:size=6518, offset=1064979
22:lstm-recoder:size=985, offset=1071497
23:version:size=33, offset=1072482
Training completed successfully!


Usage: unicharset_extractor [--output_unicharset filename] [--norm_mode mode] box_or_text_file [...]
Where mode means:
 1=combine graphemes (use for Latin and other simple scripts)
 2=split graphemes (use for Indic/Khmer/Myanmar)
 3=pure unicode (use for Arabic/Hebrew/Thai/Tibetan)
Reads box or plain text files to extract the unicharset.


# TH ล้วน

In [12]:
import pytesseract
from PIL import Image

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# ตั้งค่าเส้นทางให้ Tesseract ใช้โมเดลที่ฝึกเสร็จแล้ว
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" -l tha'

# โหลดรูปภาพที่ต้องการทดสอบ OCR
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'
image = Image.open(image_path)

# ทำ OCR ด้วย Tesseract
text = pytesseract.image_to_string(image, config=custom_config)

print(text)


ท ี ่ ก พ ท ๐ ๑ / ล ๑ ๕ พ ส ํ า น ั ก ง า น ก า ร บ ิ น พ ล เร ื อ น แห ่ ง ป ร ะ เท ศ ไ ท ย

' ๒ ๒ ๒ ขอ ย ว ิ ภา ว ต ี ร ั ง ส ิ ต ๒ ๕

ถ ถ น น ว ิ ภา ว ด ี ร ั ง ส ิ ต แข ว ง จ ต ุ จ ั ก ร

. เ ข ต จ ต ุ จ ั ก ร ก ร ุ ง เท พ ม ห า น ค ร ๑ ๐ ๓ ๐ ๐

0 ก ุ ม ภา พ ั น ธ์ ๒ ๕ ๒ ๓
เร ื ่ อ ง ก า ร อ น ุ ญา ต บ ั ง ค ั บ ห ร ื อ ป ล ่ อ ย อ า ก า ศ ย า น ซึ ่ ง ไม ่ ม ี น ั ก บ ิ น ใน พ ื ้ น ท ี ่ อ ั น ต ร า ย
เร ี ย น น า ย ก ั น ย ์ ว ิ ร ย ศิ ร ิ
ต า ม ท ี ่ ท ่ า น ม ี ค ว า ม ป ร ะ ส ง ค ์ จ ะ ท ํ า ก า ร บ ิ น ถ่ า ย ภา พ น ึ ่ ง แล ะ ภา พ เค ล ื ่ อ น ไห ว ใน ม ุ ม ส ู ง

จ ึ ง ขอ อ น ุ ญา ต บ ั ง ค ั บ ห ร ื อ ป ล ่ อ ย อ า ก า ศ ย า น ซึ่ ง ไม ่ ม ี น ั ก บ ื น ต า ม ห น ั ง ส ื อ ก า ร ขึ ้ น ท ะ เบ ี ย น ผู้ บ ั ง ค ั บ ห ร ื อ ป ล ่ อ ย
อ า ก า ศ ย า น ซึ ่ ง ไม ่ ม ี น ั ก บ ิ น เล ข ท ี ่ ๐ ๑ ๐ ๒ ๕ ๒ / ๒ ๕ ๒ ๒ แบ บ !/ บ เป ่ ศิ ๐ ๒ ๐ «ย่ ห ้ อ 00| รุ่น ม ย 3 ห ม า ย เล ข เค ร ื ่ อ ง
1561 ค ร ท 4๕22640026970 ท ํ า ก า ร บ ิ น ใน ว ั น ท ี ่ ๕ - ๓ ก ุ ม ภา พ ั น ธ์ ๒ ๕ ๒ ๓ ช่

# TH + ENG

In [11]:
import pytesseract
from PIL import Image

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# ตั้งค่าเส้นทางให้ Tesseract ใช้โมเดลที่ฝึกเสร็จแล้ว
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" -l tha+eng'

# โหลดรูปภาพที่ต้องการทดสอบ OCR
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'
image = Image.open(image_path)

# ทำ OCR ด้วย Tesseract
text = pytesseract.image_to_string(image, config=custom_config)

print(text)


ท ี ่ ก พ ท ๐ ๑ / ล ๑ ๕ พ ส ํ า น ั ก ง า น ก า ร บ ิ น พ ล เร ื อ น แห ่ ง ป ร ะ เท ศ ไ ท ย

' ๒ ๒ ๒ ขอ ย ว ิ ภา ว ต ี ร ั ง ส ิ ต ๒ ๕

ถ ถ น น ว ิ ภา ว ด ี ร ั ง ส ิ ต แข ว ง จ ต ุ จ ั ก ร

. เ ข ต จ ต ุ จ ั ก ร ก ร ุ ง เท พ ม ห า น ค ร ๑ ๐ ๓ ๐ ๐

5 ก ุ ม ภา พ ั น ธ์ ๒ ๕ ๒ ๓
เร ื ่ อ ง ก า ร อ น ุ ญา ต บ ั ง ค ั บ ห ร ื อ ป ล ่ อ ย อ า ก า ศ ย า น ซึ ่ ง ไม ่ ม ี น ั ก บ ิ น ใน พ ื ้ น ท ี ่ อ ั น ต ร า ย
เร ี ย น น า ย ก ั น ย ์ ว ิ ร ย ศิ ร ิ
ต า ม ท ี ่ ท ่ า น ม ี ค ว า ม ป ร ะ ส ง ค ์ จ ะ ท ํ า ก า ร บ ิ น ถ่ า ย ภา พ น ึ ่ ง แล ะ ภา พ เค ล ื ่ อ น ไห ว ใน ม ุ ม ส ู ง

จ ึ ง ขอ อ น ุ ญา ต บ ั ง ค ั บ ห ร ื อ ป ล ่ อ ย อ า ก า ศ ย า น ซึ่ ง ไม ่ ม ี น ั ก บ ื น ต า ม ห น ั ง ส ื อ ก า ร ขึ ้ น ท ะ เบ ี ย น ผู้ บ ั ง ค ั บ ห ร ื อ ป ล ่ อ ย
อ า ก า ศ ย า น ซึ ่ ง ไม ่ ม ี น ั ก บ ิ น เล ข ท ี ่ ๐ ๑ ๐ ๒ ๕ ๒ / ๒ ๕ ๒ ๒ แบ บ !/ บ เป ่ ศิ ๐ ๒ ๐ «ย่ ห ้ อ DI รุ่น ม ย 3 ห ม า ย เล ข เค ร ื ่ อ ง
1561 ค ร ท 4๕22640026970 ท ํ า ก า ร บ ิ น ใน ว ั น ท ี ่ ๕ - ๓ ก ุ ม ภา พ ั น ธ์ ๒ ๕ ๒ ๓ ช่ 

# extended export file

In [1]:
import pytesseract
from PIL import Image
import cv2

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# Path to the output text file
output_text_file = '/Users/gunnviryasiri/Desktop/ocr/11jul_7777777.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using Thai and English languages
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
text = pytesseract.image_to_string(gray, config=custom_config, lang='tha+eng')

# Save the extracted text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text)

print(f'Text extracted and saved to {output_text_file}')


Text extracted and saved to /Users/gunnviryasiri/Desktop/ocr/11jul_7777777.txt


## แก้ name format

In [7]:
import pytesseract
from PIL import Image
import cv2
from datetime import datetime

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# สร้างชื่อไฟล์จากวันที่และเวลา
current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
output_text_file = f'/Users/gunnviryasiri/Desktop/ocr/results/ocr_\{current_time}.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using Thai and English languages
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
text = pytesseract.image_to_string(gray, config=custom_config, lang='tha+eng')

# Save the extracted text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text)

print(f'Text extracted and saved to {output_text_file}')


Text extracted and saved to /Users/gunnviryasiri/Desktop/ocr/results/ocr20240811_194229.txt


## ลบช่องว่างด้วย " " > ""

In [9]:
import pytesseract
from PIL import Image
import cv2
from datetime import datetime

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# สร้างชื่อไฟล์จากวันที่และเวลา
current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
output_text_file = f'/Users/gunnviryasiri/Desktop/ocr/results/ocr_output_{current_time}.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using Thai and English languages
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
text = pytesseract.image_to_string(gray, config=custom_config, lang='tha+eng')

# ลบช่องว่างทั้งหมดออกจากข้อความที่ได้
text_no_spaces = text.replace(" ", "")

# Save the cleaned text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text_no_spaces)

print(f'Text extracted, cleaned, and saved to {output_text_file}')


Text extracted, cleaned, and saved to /Users/gunnviryasiri/Desktop/ocr/results/ocr_output_20240811_194635.txt


### confusion matric

In [1]:
import pytesseract
from PIL import Image
from datetime import datetime
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# สร้างชื่อไฟล์จากวันที่และเวลา
current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
output_text_file = f'/Users/gunnviryasiri/Desktop/ocr/results/ocr_output_{current_time}.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using Thai and English languages
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
text = pytesseract.image_to_string(gray, config=custom_config, lang='tha+eng')

# ลบช่องว่างทั้งหมดออกจากข้อความที่ได้
text_no_spaces = text.replace(" ", "")

# Save the cleaned text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text_no_spaces)

print(f'Text extracted, cleaned, and saved to {output_text_file}')

# อ่านข้อความจากไฟล์ FORTEST.txt
with open('/Users/gunnviryasiri/Desktop/ocr/results/FORTEST.txt', 'r', encoding='utf-8') as f:
    for_test_text = f.read().replace(" ", "")

# อ่านข้อความที่ได้จาก OCR
with open(output_text_file, 'r', encoding='utf-8') as f:
    ocr_text = f.read()

# สร้าง list ของตัวอักษรจากข้อความ
for_test_chars = list(for_test_text)
ocr_chars = list(ocr_text)

# ปรับขนาดของลิสต์ให้ตรงกัน
max_len = max(len(for_test_chars), len(ocr_chars))
for_test_chars = for_test_chars + [''] * (max_len - len(for_test_chars))
ocr_chars = ocr_chars + [''] * (max_len - len(ocr_chars))

# สร้าง confusion matrix
cm = confusion_matrix(for_test_chars, ocr_chars, labels=np.unique(for_test_chars + ocr_chars))

# แสดง confusion matrix
print("Confusion Matrix:")
print(cm)

# แสดงผล classification report
print("Classification Report:")
print(classification_report(for_test_chars, ocr_chars))


Text extracted, cleaned, and saved to /Users/gunnviryasiri/Desktop/ocr/results/ocr_output_20240811_221609.txt
Confusion Matrix:
[[ 0  0  0 ...  0  0  0]
 [ 1 15  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
Classification Report:
              precision    recall  f1-score   support

                   0.00      0.00      0.00         0
           
       0.43      0.43      0.43        35
           !       0.50      1.00      0.67         1
           #       1.00      1.00      1.00         1
           %       0.00      0.00      0.00         0
           (       0.20      0.20      0.20         5
           )       0.20      0.20      0.20         5
           -       0.60      0.60      0.60         5
           .       0.25      0.20      0.22        10
           /       0.50      0.33      0.40         3
           0       0.29      0.50      0.36         4
           1       0.25      0.33      0.29 

/Users/gunnviryasiri/.pyenv/versions/3.11.0/envs/myenv3110/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/gunnviryasiri/.pyenv/versions/3.11.0/envs/myenv3110/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/gunnviryasiri/.pyenv/versions/3.11.0/envs/myenv3110/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control t


## ความหมาย
- Precision: ความถูกต้องของการทำนายว่าเป็นตัวอักษรที่เฉพาะเจาะจง
- Recall: ความสามารถในการจับคู่ตัวอักษรที่เป็นจริงในข้อความ
- F1-score: ความสมดุลระหว่าง Precision และ Recall
- Support: จำนวนตัวอย่างที่มีตัวอักษรนั้น
### ผล
- Precision และ Recall: ตัวอักษรบางตัวมี precision และ recall ต่ำ อาจหมายความว่าการ OCR ยังไม่สามารถจับคู่ได้ดี หรือมีตัวอักษรที่ไม่ค่อยเห็นในข้อมูลฝึกหัด
- Accuracy: 0.42 หมายความว่า OCR มีความแม่นยำประมาณ 42% ซึ่งถือว่าต่ำ คุณอาจต้องพิจารณาปรับปรุงคุณภาพของภาพหรือการตั้งค่า Tesseract เพื่อเพิ่มความแม่นยำ

# New Confusion 
- ไม่ใช้ library
- ใช้อันที่เทรนมา

In [1]:
import pytesseract
from PIL import Image
import cv2
from datetime import datetime

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# Path to the reference file
reference_text_file = '/Users/gunnviryasiri/Desktop/ocr/results/FORTEST.txt'

# สร้างชื่อไฟล์จากวันที่และเวลา
current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
output_text_file = f'/Users/gunnviryasiri/Desktop/ocr/results/ocr_output_{current_time}.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using Thai and English languages
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
text = pytesseract.image_to_string(gray, config=custom_config, lang='tha+eng')

# ลบช่องว่างทั้งหมดออกจากข้อความที่ได้
text_no_spaces = text.replace(" ", "")

# Save the cleaned text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text_no_spaces)

# อ่านข้อความที่ถูกต้องจากไฟล์ reference
with open(reference_text_file, 'r', encoding='utf-8') as f:
    correct_text = f.read().replace(" ", "")

# เปรียบเทียบข้อความและสร้าง confusion matrix
tp = tn = fp = fn = 0

# ตรวจสอบความยาวของข้อความทั้งสองก่อนเปรียบเทียบ
min_length = min(len(text_no_spaces), len(correct_text))

for i in range(min_length):
    if text_no_spaces[i] == correct_text[i]:
        tp += 1  # True Positive
    else:
        fp += 1  # False Positive

# กรณีข้อความที่ OCR สั้นกว่าข้อความที่ถูกต้อง
if len(text_no_spaces) < len(correct_text):
    fn += len(correct_text) - len(text_no_spaces)  # False Negative: ข้อความหายไป

# กรณีข้อความที่ OCR ยาวกว่าข้อความที่ถูกต้อง
if len(text_no_spaces) > len(correct_text):
    fp += len(text_no_spaces) - len(correct_text)  # False Positive: ข้อความเกินมา

# แสดงผลลัพธ์ Confusion Matrix
print(f"True Positive (TP): {tp}")
print(f"False Positive (FP): {fp}")
print(f"False Negative (FN): {fn}")
# เราไม่สามารถตรวจสอบ True Negative ได้ (เพราะไม่มีข้อมูลที่ไม่ได้มีอยู่จริงในภาพ)

accuracy = tp / (tp + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')


print(f'Text extracted, cleaned, and saved to {output_text_file}')


True Positive (TP): 839
False Positive (FP): 1172
False Negative (FN): 5
Accuracy: 0.42
Precision: 0.42
Recall: 0.99
Text extracted, cleaned, and saved to /Users/gunnviryasiri/Desktop/ocr/results/ocr_output_20240826_150830.txt


- ใช้อัน library tesseract

In [12]:
import pytesseract
from PIL import Image
import cv2
from datetime import datetime

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# Path to the reference file
reference_text_file = '/Users/gunnviryasiri/Desktop/ocr/results/FORTEST.txt'

# สร้างชื่อไฟล์จากวันที่และเวลา
current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
output_text_file = f'/Users/gunnviryasiri/Desktop/ocr/results/ocr_output_{current_time}.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using Thai and English languages
# custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
# text = pytesseract.image_to_string(gray, config=custom_config, lang='tha+eng')
text = pytesseract.image_to_string(gray, lang='tha+eng')

# ลบช่องว่างทั้งหมดออกจากข้อความที่ได้
text_no_spaces = text.replace(" ", "")

# Save the cleaned text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text_no_spaces)

# อ่านข้อความที่ถูกต้องจากไฟล์ reference
with open(reference_text_file, 'r', encoding='utf-8') as f:
    correct_text = f.read().replace(" ", "")

# เปรียบเทียบข้อความและสร้าง confusion matrix
tp = tn = fp = fn = 0

# ตรวจสอบความยาวของข้อความทั้งสองก่อนเปรียบเทียบ
min_length = min(len(text_no_spaces), len(correct_text))

for i in range(min_length):
    if text_no_spaces[i] == correct_text[i]:
        tp += 1  # True Positive
    else:
        fp += 1  # False Positive

# กรณีข้อความที่ OCR สั้นกว่าข้อความที่ถูกต้อง
if len(text_no_spaces) < len(correct_text):
    fn += len(correct_text) - len(text_no_spaces)  # False Negative: ข้อความหายไป

# กรณีข้อความที่ OCR ยาวกว่าข้อความที่ถูกต้อง
if len(text_no_spaces) > len(correct_text):
    fp += len(text_no_spaces) - len(correct_text)  # False Positive: ข้อความเกินมา

# แสดงผลลัพธ์ Confusion Matrix
print(f"True Positive (TP): {tp}")
print(f"False Positive (FP): {fp}")
print(f"False Negative (FN): {fn}")
# เราไม่สามารถตรวจสอบ True Negative ได้ (เพราะไม่มีข้อมูลที่ไม่ได้มีอยู่จริงในภาพ)

accuracy = tp / (tp + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')


print(f'Text extracted, cleaned, and saved to {output_text_file}')


True Positive (TP): 340
False Positive (FP): 1672
False Negative (FN): 4
Accuracy: 0.17
Precision: 0.17
Recall: 0.99
Text extracted, cleaned, and saved to /Users/gunnviryasiri/Desktop/ocr/results/ocr_output_20240824_140146.txt


- Change other model

In [ ]:
import os
import pytesseract
from PIL import Image
from datetime import datetime

# ตั้งค่า TESSDATA_PREFIX
os.environ['TESSDATA_PREFIX'] = '/Users/gunnviryasiri/pythainlp-data/'

# ตั้งค่าเส้นทางไปยัง Tesseract executable
pytesseract.pytesseract.tesseract_cmd = r'/opt/homebrew/bin/tesseract'

# Path to the image file
image_path = '/Users/gunnviryasiri/Desktop/ocr/testfile/file1.jpg'

# Path to the reference file
reference_text_file = '/Users/gunnviryasiri/Desktop/ocr/results/FORTEST.txt'

# สร้างชื่อไฟล์จากวันที่และเวลา
current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
output_text_file = f'/Users/gunnviryasiri/Desktop/ocr/results/ocr_output_{current_time}.txt'

# Load the image
image = Image.open(image_path)

# Convert the image to grayscale
gray = image.convert('L')

# Perform OCR on the image using the custom model
custom_config = r'--tessdata-dir "/Users/gunnviryasiri/pythainlp-data/tessdata" --oem 3 --psm 6'
text = pytesseract.image_to_string(gray, config=custom_config, lang='gunn')

# ลบช่องว่างทั้งหมดออกจากข้อความที่ได้
text_no_spaces = text.replace(" ", "")

# Save the cleaned text to a file
with open(output_text_file, 'w', encoding='utf-8') as f:
    f.write(text_no_spaces)

# อ่านข้อความที่ถูกต้องจากไฟล์ reference
with open(reference_text_file, 'r', encoding='utf-8') as f:
    correct_text = f.read().replace(" ", "")

# เปรียบเทียบข้อความและสร้าง confusion matrix
tp = tn = fp = fn = 0

# ตรวจสอบความยาวของข้อความทั้งสองก่อนเปรียบเทียบ
min_length = min(len(text_no_spaces), len(correct_text))

for i in range(min_length):
    if text_no_spaces[i] == correct_text[i]:
        tp += 1  # True Positive
    else:
        fp += 1  # False Positive

# กรณีข้อความที่ OCR สั้นกว่าข้อความที่ถูกต้อง
if len(text_no_spaces) < len(correct_text):
    fn += len(correct_text) - len(text_no_spaces)  # False Negative: ข้อความหายไป

# กรณีข้อความที่ OCR ยาวกว่าข้อความที่ถูกต้อง
if len(text_no_spaces) > len(correct_text):
    fp += len(text_no_spaces) - len(correct_text)  # False Positive: ข้อความเกินมา

# แสดงผลลัพธ์ Confusion Matrix
print(f"True Positive (TP): {tp}")
print(f"False Positive (FP): {fp}")
print(f"False Negative (FN): {fn}")
# เราไม่สามารถตรวจสอบ True Negative ได้ (เพราะไม่มีข้อมูลที่ไม่ได้มีอยู่จริงในภาพ)

accuracy = tp / (tp + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')

print(f'Text extracted, cleaned, and saved to {output_text_file}')
